<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resultset [
  <!ELEMENT resultset (row*)>
  <!ELEMENT row (field*)>
  <!ELEMENT field (#PCDATA)>
  <!ATTLIST field name CDATA #REQUIRED>
]>

<resultset>
  <row>
	<field name="customerNumber">103</field>
	<field name="customerName">Atelier graphique</field>
	<field name="contactLastName">Schmitt</field>
	<field name="contactFirstName">Carine </field>
	<field name="phone">40.32.2555</field>
	<field name="addressLine1">54, rue Royale</field>
	<field name="addressLine2" />
	<field name="city">Nantes</field>
	<field name="state" />
	<field name="postalCode">44000</field>
	<field name="country">France</field>
	<field name="salesRepEmployeeNumber">1370</field>
	<field name="creditLimit">21000.00</field>
  </row>

  <row>
	<field name="customerNumber">112</field>
	<field name="customerName">Signal Gift Stores</field>
	<field name="contactLastName">King</field>
	<field name="contactFirstName">Jean</field>
	<field name="phone">7025551838</field>
	<field name="addressLine1">8489 Strong St.</field>
	<field name="addressLine2" />
	<field name="city">Las Vegas</field>
	<field name="state">NV</field>
	<field name="postalCode">83030</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1166</field>
	<field name="creditLimit">71800.00</field>
  </row>

  <row>
	<field name="customerNumber">114</field>
	<field name="customerName">Australian Collectors, Co.</field>
	<field name="contactLastName">Ferguson</field>
	<field name="contactFirstName">Peter</field>
	<field name="phone">03 9520 4555</field>
	<field name="addressLine1">636 St Kilda Road</field>
	<field name="addressLine2">Level 3</field>
	<field name="city">Melbourne</field>
	<field name="state">Victoria</field>
	<field name="postalCode">3004</field>
	<field name="country">Australia</field>
	<field name="salesRepEmployeeNumber">1611</field>
	<field name="creditLimit">117300.00</field>
  </row>

  <row>
	<field name="customerNumber">119</field>
	<field name="customerName">La Rochelle Gifts</field>
	<field name="contactLastName">Labrune</field>
	<field name="contactFirstName">Janine </field>
	<field name="phone">40.67.8555</field>
	<field name="addressLine1">67, rue des Cinquante Otages</field>
	<field name="addressLine2" />
	<field name="city">Nantes</field>
	<field name="state" />
	<field name="postalCode">44000</field>
	<field name="country">France</field>
	<field name="salesRepEmployeeNumber">1370</field>
	<field name="creditLimit">118200.00</field>
  </row>

  <row>
	<field name="customerNumber">121</field>
	<field name="customerName">Baane Mini Imports</field>
	<field name="contactLastName">Bergulfsen</field>
	<field name="contactFirstName">Jonas </field>
	<field name="phone">07-98 9555</field>
	<field name="addressLine1">Erling Skakkes gate 78</field>
	<field name="addressLine2" />
	<field name="city">Stavern</field>
	<field name="state" />
	<field name="postalCode">4110</field>
	<field name="country">Norway</field>
	<field name="salesRepEmployeeNumber">1504</field>
	<field name="creditLimit">81700.00</field>
  </row>

  <row>
	<field name="customerNumber">124</field>
	<field name="customerName">Mini Gifts Distributors Ltd.</field>
	<field name="contactLastName">Nelson</field>
	<field name="contactFirstName">Susan</field>
	<field name="phone">4155551450</field>
	<field name="addressLine1">5677 Strong St.</field>
	<field name="addressLine2" />
	<field name="city">San Rafael</field>
	<field name="state">CA</field>
	<field name="postalCode">97562</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1165</field>
	<field name="creditLimit">210500.00</field>
  </row>

  <row>
	<field name="customerNumber">125</field>
	<field name="customerName">Havel andamp; Zbyszek Co</field>
	<field name="contactLastName">Piestrzeniewicz</field>
	<field name="contactFirstName">Zbyszek </field>
	<field name="phone">(26) 642-7555</field>
	<field name="addressLine1">ul. Filtrowa 68</field>
	<field name="addressLine2" />
	<field name="city">Warszawa</field>
	<field name="state" />
	<field name="postalCode">01-012</field>
	<field name="country">Poland</field>
	<field name="salesRepEmployeeNumber" />
	<field name="creditLimit">0.00</field>
  </row>

  <row>
	<field name="customerNumber">128</field>
	<field name="customerName">Blauer See Auto, Co.</field>
	<field name="contactLastName">Keitel</field>
	<field name="contactFirstName">Roland</field>
	<field name="phone">+49 69 66 90 2555</field>
	<field name="addressLine1">Lyonerstr. 34</field>
	<field name="addressLine2" />
	<field name="city">Frankfurt</field>
	<field name="state" />
	<field name="postalCode">60528</field>
	<field name="country">Germany</field>
	<field name="salesRepEmployeeNumber">1504</field>
	<field name="creditLimit">59700.00</field>
  </row>

  <row>
	<field name="customerNumber">129</field>
	<field name="customerName">Mini Wheels Co.</field>
	<field name="contactLastName">Murphy</field>
	<field name="contactFirstName">Julie</field>
	<field name="phone">6505555787</field>
	<field name="addressLine1">5557 North Pendale Street</field>
	<field name="addressLine2" />
	<field name="city">San Francisco</field>
	<field name="state">CA</field>
	<field name="postalCode">94217</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1165</field>
	<field name="creditLimit">64600.00</field>
  </row>

  <row>
	<field name="customerNumber">131</field>
	<field name="customerName">Land of Toys Inc.</field>
	<field name="contactLastName">Lee</field>
	<field name="contactFirstName">Kwai</field>
	<field name="phone">2125557818</field>
	<field name="addressLine1">897 Long Airport Avenue</field>
	<field name="addressLine2" />
	<field name="city">NYC</field>
	<field name="state">NY</field>
	<field name="postalCode">10022</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1323</field>
	<field name="creditLimit">114900.00</field>
  </row>

  <row>
	<field name="customerNumber">141</field>
	<field name="customerName">Euro+ Shopping Channel</field>
	<field name="contactLastName">Freyre</field>
	<field name="contactFirstName">Diego </field>
	<field name="phone">(91) 555 94 44</field>
	<field name="addressLine1">C/ Moralzarzal, 86</field>
	<field name="addressLine2" />
	<field name="city">Madrid</field>
	<field name="state" />
	<field name="postalCode">28034</field>
	<field name="country">Spain</field>
	<field name="salesRepEmployeeNumber">1370</field>
	<field name="creditLimit">227600.00</field>
  </row>

  <row>
	<field name="customerNumber">144</field>
	<field name="customerName">Volvo Model Replicas, Co</field>
	<field name="contactLastName">Berglund</field>
	<field name="contactFirstName">Christina </field>
	<field name="phone">0921-12 3555</field>
	<field name="addressLine1">Berguvsv├ñgen  8</field>
	<field name="addressLine2" />
	<field name="city">Lule├Ñ</field>
	<field name="state" />
	<field name="postalCode">S-958 22</field>
	<field name="country">Sweden</field>
	<field name="salesRepEmployeeNumber">1504</field>
	<field name="creditLimit">53100.00</field>
  </row>

  <row>
	<field name="customerNumber">145</field>
	<field name="customerName">Danish Wholesale Imports</field>
	<field name="contactLastName">Petersen</field>
	<field name="contactFirstName">Jytte </field>
	<field name="phone">31 12 3555</field>
	<field name="addressLine1">Vinb├ªltet 34</field>
	<field name="addressLine2" />
	<field name="city">Kobenhavn</field>
	<field name="state" />
	<field name="postalCode">1734</field>
	<field name="country">Denmark</field>
	<field name="salesRepEmployeeNumber">1401</field>
	<field name="creditLimit">83400.00</field>
  </row>

  <row>
	<field name="customerNumber">146</field>
	<field name="customerName">Saveley andamp; Henriot, Co.</field>
	<field name="contactLastName">Saveley</field>
	<field name="contactFirstName">Mary </field>
	<field name="phone">78.32.5555</field>
	<field name="addressLine1">2, rue du Commerce</field>
	<field name="addressLine2" />
	<field name="city">Lyon</field>
	<field name="state" />
	<field name="postalCode">69004</field>
	<field name="country">France</field>
	<field name="salesRepEmployeeNumber">1337</field>
	<field name="creditLimit">123900.00</field>
  </row>

  <row>
	<field name="customerNumber">148</field>
	<field name="customerName">Dragon Souveniers, Ltd.</field>
	<field name="contactLastName">Natividad</field>
	<field name="contactFirstName">Eric</field>
	<field name="phone">+65 221 7555</field>
	<field name="addressLine1">Bronz Sok.</field>
	<field name="addressLine2">Bronz Apt. 3/6 Tesvikiye</field>
	<field name="city">Singapore</field>
	<field name="state" />
	<field name="postalCode">079903</field>
	<field name="country">Singapore</field>
	<field name="salesRepEmployeeNumber">1621</field>
	<field name="creditLimit">103800.00</field>
  </row>

  <row>
	<field name="customerNumber">151</field>
	<field name="customerName">Muscle Machine Inc</field>
	<field name="contactLastName">Young</field>
	<field name="contactFirstName">Jeff</field>
	<field name="phone">2125557413</field>
	<field name="addressLine1">4092 Furth Circle</field>
	<field name="addressLine2">Suite 400</field>
	<field name="city">NYC</field>
	<field name="state">NY</field>
	<field name="postalCode">10022</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1286</field>
	<field name="creditLimit">138500.00</field>
  </row>

  <row>
	<field name="customerNumber">157</field>
	<field name="customerName">Diecast Classics Inc.</field>
	<field name="contactLastName">Leong</field>
	<field name="contactFirstName">Kelvin</field>
	<field name="phone">2155551555</field>
	<field name="addressLine1">7586 Pompton St.</field>
	<field name="addressLine2" />
	<field name="city">Allentown</field>
	<field name="state">PA</field>
	<field name="postalCode">70267</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1216</field>
	<field name="creditLimit">100600.00</field>
  </row>

  <row>
	<field name="customerNumber">161</field>
	<field name="customerName">Technics Stores Inc.</field>
	<field name="contactLastName">Hashimoto</field>
	<field name="contactFirstName">Juri</field>
	<field name="phone">6505556809</field>
	<field name="addressLine1">9408 Furth Circle</field>
	<field name="addressLine2" />
	<field name="city">Burlingame</field>
	<field name="state">CA</field>
	<field name="postalCode">94217</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1165</field>
	<field name="creditLimit">84600.00</field>
  </row>

  <row>
	<field name="customerNumber">166</field>
	<field name="customerName">Handji Giftsandamp; Co</field>
	<field name="contactLastName">Victorino</field>
	<field name="contactFirstName">Wendy</field>
	<field name="phone">+65 224 1555</field>
	<field name="addressLine1">106 Linden Road Sandown</field>
	<field name="addressLine2">2nd Floor</field>
	<field name="city">Singapore</field>
	<field name="state" />
	<field name="postalCode">069045</field>
	<field name="country">Singapore</field>
	<field name="salesRepEmployeeNumber">1612</field>
	<field name="creditLimit">97900.00</field>
  </row>

  <row>
	<field name="customerNumber">167</field>
	<field name="customerName">Herkku Gifts</field>
	<field name="contactLastName">Oeztan</field>
	<field name="contactFirstName">Veysel</field>
	<field name="phone">+47 2267 3215</field>
	<field name="addressLine1">Brehmen St. 121</field>
	<field name="addressLine2">PR 334 Sentrum</field>
	<field name="city">Bergen</field>
	<field name="state" />
	<field name="postalCode">N 5804</field>
	<field name="country">Norway  </field>
	<field name="salesRepEmployeeNumber">1504</field>
	<field name="creditLimit">96800.00</field>
  </row>

  <row>
	<field name="customerNumber">168</field>
	<field name="customerName">American Souvenirs Inc</field>
	<field name="contactLastName">Franco</field>
	<field name="contactFirstName">Keith</field>
	<field name="phone">2035557845</field>
	<field name="addressLine1">149 Spinnaker Dr.</field>
	<field name="addressLine2">Suite 101</field>
	<field name="city">New Haven</field>
	<field name="state">CT</field>
	<field name="postalCode">97823</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1286</field>
	<field name="creditLimit">0.00</field>
  </row>

  <row>
	<field name="customerNumber">169</field>
	<field name="customerName">Porto Imports Co.</field>
	<field name="contactLastName">de Castro</field>
	<field name="contactFirstName">Isabel </field>
	<field name="phone">(1) 356-5555</field>
	<field name="addressLine1">Estrada da sa├║de n. 58</field>
	<field name="addressLine2" />
	<field name="city">Lisboa</field>
	<field name="state" />
	<field name="postalCode">1756</field>
	<field name="country">Portugal</field>
	<field name="salesRepEmployeeNumber" />
	<field name="creditLimit">0.00</field>
  </row>

  <row>
	<field name="customerNumber">171</field>
	<field name="customerName">Daedalus Designs Imports</field>
	<field name="contactLastName">Ranc├®</field>
	<field name="contactFirstName">Martine </field>
	<field name="phone">20.16.1555</field>
	<field name="addressLine1">184, chauss├®e de Tournai</field>
	<field name="addressLine2" />
	<field name="city">Lille</field>
	<field name="state" />
	<field name="postalCode">59000</field>
	<field name="country">France</field>
	<field name="salesRepEmployeeNumber">1370</field>
	<field name="creditLimit">82900.00</field>
  </row>

  <row>
	<field name="customerNumber">172</field>
	<field name="customerName">La Corne D'abondance, Co.</field>
	<field name="contactLastName">Bertrand</field>
	<field name="contactFirstName">Marie</field>
	<field name="phone">(1) 42.34.2555</field>
	<field name="addressLine1">265, boulevard Charonne</field>
	<field name="addressLine2" />
	<field name="city">Paris</field>
	<field name="state" />
	<field name="postalCode">75012</field>
	<field name="country">France</field>
	<field name="salesRepEmployeeNumber">1337</field>
	<field name="creditLimit">84300.00</field>
  </row>

  <row>
	<field name="customerNumber">173</field>
	<field name="customerName">Cambridge Collectables Co.</field>
	<field name="contactLastName">Tseng</field>
	<field name="contactFirstName">Jerry</field>
	<field name="phone">6175555555</field>
	<field name="addressLine1">4658 Baden Av.</field>
	<field name="addressLine2" />
	<field name="city">Cambridge</field>
	<field name="state">MA</field>
	<field name="postalCode">51247</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1188</field>
	<field name="creditLimit">43400.00</field>
  </row>

  <row>
	<field name="customerNumber">175</field>
	<field name="customerName">Gift Depot Inc.</field>
	<field name="contactLastName">King</field>
	<field name="contactFirstName">Julie</field>
	<field name="phone">2035552570</field>
	<field name="addressLine1">25593 South Bay Ln.</field>
	<field name="addressLine2" />
	<field name="city">Bridgewater</field>
	<field name="state">CT</field>
	<field name="postalCode">97562</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1323</field>
	<field name="creditLimit">84300.00</field>
  </row>

  <row>
	<field name="customerNumber">177</field>
	<field name="customerName">Osaka Souveniers Co.</field>
	<field name="contactLastName">Kentary</field>
	<field name="contactFirstName">Mory</field>
	<field name="phone">+81 06 6342 5555</field>
	<field name="addressLine1">1-6-20 Dojima</field>
	<field name="addressLine2" />
	<field name="city">Kita-ku</field>
	<field name="state">Osaka</field>
	<field name="postalCode"> 530-0003</field>
	<field name="country">Japan</field>
	<field name="salesRepEmployeeNumber">1621</field>
	<field name="creditLimit">81200.00</field>
  </row>

  <row>
	<field name="customerNumber">181</field>
	<field name="customerName">Vitachrome Inc.</field>
	<field name="contactLastName">Frick</field>
	<field name="contactFirstName">Michael</field>
	<field name="phone">2125551500</field>
	<field name="addressLine1">2678 Kingston Rd.</field>
	<field name="addressLine2">Suite 101</field>
	<field name="city">NYC</field>
	<field name="state">NY</field>
	<field name="postalCode">10022</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1286</field>
	<field name="creditLimit">76400.00</field>
  </row>

  <row>
	<field name="customerNumber">186</field>
	<field name="customerName">Toys of Finland, Co.</field>
	<field name="contactLastName">Karttunen</field>
	<field name="contactFirstName">Matti</field>
	<field name="phone">90-224 8555</field>
	<field name="addressLine1">Keskuskatu 45</field>
	<field name="addressLine2" />
	<field name="city">Helsinki</field>
	<field name="state" />
	<field name="postalCode">21240</field>
	<field name="country">Finland</field>
	<field name="salesRepEmployeeNumber">1501</field>
	<field name="creditLimit">96500.00</field>
  </row>

  <row>
	<field name="customerNumber">187</field>
	<field name="customerName">AV Stores, Co.</field>
	<field name="contactLastName">Ashworth</field>
	<field name="contactFirstName">Rachel</field>
	<field name="phone">(171) 555-1555</field>
	<field name="addressLine1">Fauntleroy Circus</field>
	<field name="addressLine2" />
	<field name="city">Manchester</field>
	<field name="state" />
	<field name="postalCode">EC2 5NT</field>
	<field name="country">UK</field>
	<field name="salesRepEmployeeNumber">1501</field>
	<field name="creditLimit">136800.00</field>
  </row>

  <row>
	<field name="customerNumber">189</field>
	<field name="customerName">Clover Collections, Co.</field>
	<field name="contactLastName">Cassidy</field>
	<field name="contactFirstName">Dean</field>
	<field name="phone">+353 1862 1555</field>
	<field name="addressLine1">25 Maiden Lane</field>
	<field name="addressLine2">Floor No. 4</field>
	<field name="city">Dublin</field>
	<field name="state" />
	<field name="postalCode">2</field>
	<field name="country">Ireland</field>
	<field name="salesRepEmployeeNumber">1504</field>
	<field name="creditLimit">69400.00</field>
  </row>

  <row>
	<field name="customerNumber">198</field>
	<field name="customerName">Auto-Moto Classics Inc.</field>
	<field name="contactLastName">Taylor</field>
	<field name="contactFirstName">Leslie</field>
	<field name="phone">6175558428</field>
	<field name="addressLine1">16780 Pompton St.</field>
	<field name="addressLine2" />
	<field name="city">Brickhaven</field>
	<field name="state">MA</field>
	<field name="postalCode">58339</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1216</field>
	<field name="creditLimit">23000.00</field>
  </row>

  <row>
	<field name="customerNumber">201</field>
	<field name="customerName">UK Collectables, Ltd.</field>
	<field name="contactLastName">Devon</field>
	<field name="contactFirstName">Elizabeth</field>
	<field name="phone">(171) 555-2282</field>
	<field name="addressLine1">12, Berkeley Gardens Blvd</field>
	<field name="addressLine2" />
	<field name="city">Liverpool</field>
	<field name="state" />
	<field name="postalCode">WX1 6LT</field>
	<field name="country">UK</field>
	<field name="salesRepEmployeeNumber">1501</field>
	<field name="creditLimit">92700.00</field>
  </row>

  <row>
	<field name="customerNumber">202</field>
	<field name="customerName">Canadian Gift Exchange Network</field>
	<field name="contactLastName">Tamuri</field>
	<field name="contactFirstName">Yoshi </field>
	<field name="phone">(604) 555-3392</field>
	<field name="addressLine1">1900 Oak St.</field>
	<field name="addressLine2" />
	<field name="city">Vancouver</field>
	<field name="state">BC</field>
	<field name="postalCode">V3F 2K1</field>
	<field name="country">Canada</field>
	<field name="salesRepEmployeeNumber">1323</field>
	<field name="creditLimit">90300.00</field>
  </row>

  <row>
	<field name="customerNumber">204</field>
	<field name="customerName">Online Mini Collectables</field>
	<field name="contactLastName">Barajas</field>
	<field name="contactFirstName">Miguel</field>
	<field name="phone">6175557555</field>
	<field name="addressLine1">7635 Spinnaker Dr.</field>
	<field name="addressLine2" />
	<field name="city">Brickhaven</field>
	<field name="state">MA</field>
	<field name="postalCode">58339</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1188</field>
	<field name="creditLimit">68700.00</field>
  </row>

  <row>
	<field name="customerNumber">205</field>
	<field name="customerName">Toys4GrownUps.com</field>
	<field name="contactLastName">Young</field>
	<field name="contactFirstName">Julie</field>
	<field name="phone">6265557265</field>
	<field name="addressLine1">78934 Hillside Dr.</field>
	<field name="addressLine2" />
	<field name="city">Pasadena</field>
	<field name="state">CA</field>
	<field name="postalCode">90003</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1166</field>
	<field name="creditLimit">90700.00</field>
  </row>

  <row>
	<field name="customerNumber">206</field>
	<field name="customerName">Asian Shopping Network, Co</field>
	<field name="contactLastName">Walker</field>
	<field name="contactFirstName">Brydey</field>
	<field name="phone">+612 9411 1555</field>
	<field name="addressLine1">Suntec Tower Three</field>
	<field name="addressLine2">8 Temasek</field>
	<field name="city">Singapore</field>
	<field name="state" />
	<field name="postalCode">038988</field>
	<field name="country">Singapore</field>
	<field name="salesRepEmployeeNumber" />
	<field name="creditLimit">0.00</field>
  </row>

  <row>
	<field name="customerNumber">209</field>
	<field name="customerName">Mini Caravy</field>
	<field name="contactLastName">Citeaux</field>
	<field name="contactFirstName">Fr├®d├®rique </field>
	<field name="phone">88.60.1555</field>
	<field name="addressLine1">24, place Kl├®ber</field>
	<field name="addressLine2" />
	<field name="city">Strasbourg</field>
	<field name="state" />
	<field name="postalCode">67000</field>
	<field name="country">France</field>
	<field name="salesRepEmployeeNumber">1370</field>
	<field name="creditLimit">53800.00</field>
  </row>

  <row>
	<field name="customerNumber">211</field>
	<field name="customerName">King Kong Collectables, Co.</field>
	<field name="contactLastName">Gao</field>
	<field name="contactFirstName">Mike</field>
	<field name="phone">+852 2251 1555</field>
	<field name="addressLine1">Bank of China Tower</field>
	<field name="addressLine2">1 Garden Road</field>
	<field name="city">Central Hong Kong</field>
	<field name="state" />
	<field name="postalCode" />
	<field name="country">Hong Kong</field>
	<field name="salesRepEmployeeNumber">1621</field>
	<field name="creditLimit">58600.00</field>
  </row>

  <row>
	<field name="customerNumber">216</field>
	<field name="customerName">Enaco Distributors</field>
	<field name="contactLastName">Saavedra</field>
	<field name="contactFirstName">Eduardo </field>
	<field name="phone">(93) 203 4555</field>
	<field name="addressLine1">Rambla de Catalu├▒a, 23</field>
	<field name="addressLine2" />
	<field name="city">Barcelona</field>
	<field name="state" />
	<field name="postalCode">08022</field>
	<field name="country">Spain</field>
	<field name="salesRepEmployeeNumber">1702</field>
	<field name="creditLimit">60300.00</field>
  </row>

  <row>
	<field name="customerNumber">219</field>
	<field name="customerName">Boards andamp; Toys Co.</field>
	<field name="contactLastName">Young</field>
	<field name="contactFirstName">Mary</field>
	<field name="phone">3105552373</field>
	<field name="addressLine1">4097 Douglas Av.</field>
	<field name="addressLine2" />
	<field name="city">Glendale</field>
	<field name="state">CA</field>
	<field name="postalCode">92561</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1166</field>
	<field name="creditLimit">11000.00</field>
  </row>

  <row>
	<field name="customerNumber">223</field>
	<field name="customerName">Nat├╝rlich Autos</field>
	<field name="contactLastName">Kloss</field>
	<field name="contactFirstName">Horst </field>
	<field name="phone">0372-555188</field>
	<field name="addressLine1">Taucherstra├ƒe 10</field>
	<field name="addressLine2" />
	<field name="city">Cunewalde</field>
	<field name="state" />
	<field name="postalCode">01307</field>
	<field name="country">Germany</field>
	<field name="salesRepEmployeeNumber" />
	<field name="creditLimit">0.00</field>
  </row>

  <row>
	<field name="customerNumber">227</field>
	<field name="customerName">Heintze Collectables</field>
	<field name="contactLastName">Ibsen</field>
	<field name="contactFirstName">Palle</field>
	<field name="phone">86 21 3555</field>
	<field name="addressLine1">Smagsloget 45</field>
	<field name="addressLine2" />
	<field name="city">├àrhus</field>
	<field name="state" />
	<field name="postalCode">8200</field>
	<field name="country">Denmark</field>
	<field name="salesRepEmployeeNumber">1401</field>
	<field name="creditLimit">120800.00</field>
  </row>

  <row>
	<field name="customerNumber">233</field>
	<field name="customerName">Qu├®bec Home Shopping Network</field>
	<field name="contactLastName">Fresni├¿re</field>
	<field name="contactFirstName">Jean </field>
	<field name="phone">(514) 555-8054</field>
	<field name="addressLine1">43 rue St. Laurent</field>
	<field name="addressLine2" />
	<field name="city">Montr├®al</field>
	<field name="state">Qu├®bec</field>
	<field name="postalCode">H1J 1C3</field>
	<field name="country">Canada</field>
	<field name="salesRepEmployeeNumber">1286</field>
	<field name="creditLimit">48700.00</field>
  </row>

  <row>
	<field name="customerNumber">237</field>
	<field name="customerName">ANG Resellers</field>
	<field name="contactLastName">Camino</field>
	<field name="contactFirstName">Alejandra </field>
	<field name="phone">(91) 745 6555</field>
	<field name="addressLine1">Gran V├¡a, 1</field>
	<field name="addressLine2" />
	<field name="city">Madrid</field>
	<field name="state" />
	<field name="postalCode">28001</field>
	<field name="country">Spain</field>
	<field name="salesRepEmployeeNumber" />
	<field name="creditLimit">0.00</field>
  </row>

  <row>
	<field name="customerNumber">239</field>
	<field name="customerName">Collectable Mini Designs Co.</field>
	<field name="contactLastName">Thompson</field>
	<field name="contactFirstName">Valarie</field>
	<field name="phone">7605558146</field>
	<field name="addressLine1">361 Furth Circle</field>
	<field name="addressLine2" />
	<field name="city">San Diego</field>
	<field name="state">CA</field>
	<field name="postalCode">91217</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1166</field>
	<field name="creditLimit">105000.00</field>
  </row>

  <row>
	<field name="customerNumber">240</field>
	<field name="customerName">giftsbymail.co.uk</field>
	<field name="contactLastName">Bennett</field>
	<field name="contactFirstName">Helen </field>
	<field name="phone">(198) 555-8888</field>
	<field name="addressLine1">Garden House</field>
	<field name="addressLine2">Crowther Way 23</field>
	<field name="city">Cowes</field>
	<field name="state">Isle of Wight</field>
	<field name="postalCode">PO31 7PJ</field>
	<field name="country">UK</field>
	<field name="salesRepEmployeeNumber">1501</field>
	<field name="creditLimit">93900.00</field>
  </row>

  <row>
	<field name="customerNumber">242</field>
	<field name="customerName">Alpha Cognac</field>
	<field name="contactLastName">Roulet</field>
	<field name="contactFirstName">Annette </field>
	<field name="phone">61.77.6555</field>
	<field name="addressLine1">1 rue Alsace-Lorraine</field>
	<field name="addressLine2" />
	<field name="city">Toulouse</field>
	<field name="state" />
	<field name="postalCode">31000</field>
	<field name="country">France</field>
	<field name="salesRepEmployeeNumber">1370</field>
	<field name="creditLimit">61100.00</field>
  </row>

  <row>
	<field name="customerNumber">247</field>
	<field name="customerName">Messner Shopping Network</field>
	<field name="contactLastName">Messner</field>
	<field name="contactFirstName">Renate </field>
	<field name="phone">069-0555984</field>
	<field name="addressLine1">Magazinweg 7</field>
	<field name="addressLine2" />
	<field name="city">Frankfurt</field>
	<field name="state" />
	<field name="postalCode">60528</field>
	<field name="country">Germany</field>
	<field name="salesRepEmployeeNumber" />
	<field name="creditLimit">0.00</field>
  </row>

  <row>
	<field name="customerNumber">249</field>
	<field name="customerName">Amica Models andamp; Co.</field>
	<field name="contactLastName">Accorti</field>
	<field name="contactFirstName">Paolo </field>
	<field name="phone">011-4988555</field>
	<field name="addressLine1">Via Monte Bianco 34</field>
	<field name="addressLine2" />
	<field name="city">Torino</field>
	<field name="state" />
	<field name="postalCode">10100</field>
	<field name="country">Italy</field>
	<field name="salesRepEmployeeNumber">1401</field>
	<field name="creditLimit">113000.00</field>
  </row>

  <row>
	<field name="customerNumber">250</field>