<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resultset [
  <!ELEMENT resultset (row*)>
  <!ELEMENT row (field*)>
  <!ELEMENT field (#PCDATA)>
  <!ATTLIST field name CDATA #REQUIRED>
]>
<resultset>
  <row>
	<field name="employeeNumber">1002</field>
	<field name="lastName">Murphy</field>
	<field name="firstName">Diane</field>
	<field name="extension">x5800</field>
	<field name="email">dmurphy@classicmodelcars.com</field>
	<field name="reportsTo" />
	<field name="jobTitle">President</field>
	<field name="ofCode">1</field>
	<field name="ofCity">San Francisco</field>
	<field name="ofPhone">+1 650 219 4782</field>
	<field name="ofAdd1">100 Market Street</field>
	<field name="ofAdd2">Suite 300</field>
	<field name="ofState">CA</field>
	<field name="ofCountry">USA</field>
	<field name="ofPostalCode">94080</field>
	<field name="ofTerritory">NA</field>
  </row>

  <row>
	<field name="employeeNumber">1056</field>
	<field name="lastName">Patterson</field>
	<field name="firstName">Mary</field>
	<field name="extension">x4611</field>
	<field name="email">mpatterso@classicmodelcars.com</field>
	<field name="reportsTo">1002</field>
	<field name="jobTitle">VP Sales</field>
	<field name="ofCode">1</field>
	<field name="ofCity">San Francisco</field>
	<field name="ofPhone">+1 650 219 4782</field>
	<field name="ofAdd1">100 Market Street</field>
	<field name="ofAdd2">Suite 300</field>
	<field name="ofState">CA</field>
	<field name="ofCountry">USA</field>
	<field name="ofPostalCode">94080</field>
	<field name="ofTerritory">NA</field>
  </row>

  <row>
	<field name="employeeNumber">1076</field>
	<field name="lastName">Firrelli</field>
	<field name="firstName">Jeff</field>
	<field name="extension">x9273</field>
	<field name="email">jfirrelli@classicmodelcars.com</field>
	<field name="reportsTo">1002</field>
	<field name="jobTitle">VP Marketing</field>
	<field name="ofCode">1</field>
	<field name="ofCity">San Francisco</field>
	<field name="ofPhone">+1 650 219 4782</field>
	<field name="ofAdd1">100 Market Street</field>
	<field name="ofAdd2">Suite 300</field>
	<field name="ofState">CA</field>
	<field name="ofCountry">USA</field>
	<field name="ofPostalCode">94080</field>
	<field name="ofTerritory">NA</field>
  </row>

  <row>
	<field name="employeeNumber">1143</field>
	<field name="lastName">Bow</field>
	<field name="firstName">Anthony</field>
	<field name="extension">x5428</field>
	<field name="email">abow@classicmodelcars.com</field>
	<field name="reportsTo">1056</field>
	<field name="jobTitle">Sales Manager (NA)</field>
	<field name="ofCode">1</field>
	<field name="ofCity">San Francisco</field>
	<field name="ofPhone">+1 650 219 4782</field>
	<field name="ofAdd1">100 Market Street</field>
	<field name="ofAdd2">Suite 300</field>
	<field name="ofState">CA</field>
	<field name="ofCountry">USA</field>
	<field name="ofPostalCode">94080</field>
	<field name="ofTerritory">NA</field>
  </row>

  <row>
	<field name="employeeNumber">1165</field>
	<field name="lastName">Jennings</field>
	<field name="firstName">Leslie</field>
	<field name="extension">x3291</field>
	<field name="email">ljennings@classicmodelcars.com</field>
	<field name="reportsTo">1143</field>
	<field name="jobTitle">Sales Rep</field>
	<field name="ofCode">1</field>
	<field name="ofCity">San Francisco</field>
	<field name="ofPhone">+1 650 219 4782</field>
	<field name="ofAdd1">100 Market Street</field>
	<field name="ofAdd2">Suite 300</field>
	<field name="ofState">CA</field>
	<field name="ofCountry">USA</field>
	<field name="ofPostalCode">94080</field>
	<field name="ofTerritory">NA</field>
  </row>

  <row>
	<field name="employeeNumber">1166</field>
	<field name="lastName">Thompson</field>
	<field name="firstName">Leslie</field>
	<field name="extension">x4065</field>
	<field name="email">lthompson@classicmodelcars.com</field>
	<field name="reportsTo">1143</field>
	<field name="jobTitle">Sales Rep</field>
	<field name="ofCode">1</field>
	<field name="ofCity">San Francisco</field>
	<field name="ofPhone">+1 650 219 4782</field>
	<field name="ofAdd1">100 Market Street</field>
	<field name="ofAdd2">Suite 300</field>
	<field name="ofState">CA</field>
	<field name="ofCountry">USA</field>
	<field name="ofPostalCode">94080</field>
	<field name="ofTerritory">NA</field>
  </row>

  <row>
	<field name="employeeNumber">1188</field>
	<field name="lastName">Firrelli</field>
	<field name="firstName">Julie</field>
	<field name="extension">x2173</field>
	<field name="email">jfirrelli@classicmodelcars.com</field>
	<field name="reportsTo">1143</field>
	<field name="jobTitle">Sales Rep</field>
	<field name="ofCode">2</field>
	<field name="ofCity">Boston</field>
	<field name="ofPhone">+1 215 837 0825</field>
	<field name="ofAdd1">1550 Court Place</field>
	<field name="ofAdd2">Suite 102</field>
	<field name="ofState">MA</field>
	<field name="ofCountry">USA</field>
	<field name="ofPostalCode">02107</field>
	<field name="ofTerritory">NA</field>
  </row>

  <row>
	<field name="employeeNumber">1216</field>
	<field name="lastName">Patterson</field>
	<field name="firstName">Steve</field>
	<field name="extension">x4334</field>
	<field name="email">spatterson@classicmodelcars.com</field>
	<field name="reportsTo">1143</field>
	<field name="jobTitle">Sales Rep</field>
	<field name="ofCode">2</field>
	<field name="ofCity">Boston</field>
	<field name="ofPhone">+1 215 837 0825</field>
	<field name="ofAdd1">1550 Court Place</field>
	<field name="ofAdd2">Suite 102</field>
	<field name="ofState">MA</field>
	<field name="ofCountry">USA</field>
	<field name="ofPostalCode">02107</field>
	<field name="ofTerritory">NA</field>
  </row>

  <row>
	<field name="employeeNumber">1286</field>
	<field name="lastName">Tseng</field>
	<field name="firstName">Foon Yue</field>
	<field name="extension">x2248</field>
	<field name="email">ftseng@classicmodelcars.com</field>
	<field name="reportsTo">1143</field>
	<field name="jobTitle">Sales Rep</field>
	<field name="ofCode">3</field>
	<field name="ofCity">NYC</field>
	<field name="ofPhone">+1 212 555 3000</field>
	<field name="ofAdd1">523 East 53rd Street</field>
	<field name="ofAdd2">apt. 5A</field>
	<field name="ofState">NY</field>
	<field name="ofCountry">USA</field>
	<field name="ofPostalCode">10022</field>
	<field name="ofTerritory">NA</field>
  </row>

  <row>
	<field name="employeeNumber">1323</field>
	<field name="lastName">Vanauf</field>
	<field name="firstName">George</field>
	<field name="extension">x4102</field>
	<field name="email">gvanauf@classicmodelcars.com</field>
	<field name="reportsTo">1143</field>
	<field name="jobTitle">Sales Rep</field>
	<field name="ofCode">3</field>
	<field name="ofCity">NYC</field>
	<field name="ofPhone">+1 212 555 3000</field>
	<field name="ofAdd1">523 East 53rd Street</field>
	<field name="ofAdd2">apt. 5A</field>
	<field name="ofState">NY</field>
	<field name="ofCountry">USA</field>
	<field name="ofPostalCode">10022</field>
	<field name="ofTerritory">NA</field>
  </row>

  <row>
	<field name="employeeNumber">1102</field>
	<field name="lastName">Bondur</field>
	<field name="firstName">Gerard</field>
	<field name="extension">x5408</field>
	<field name="email">gbondur@classicmodelcars.com</field>
	<field name="reportsTo">1056</field>
	<field name="jobTitle">Sale Manager (EMEA)</field>
	<field name="ofCode">4</field>
	<field name="ofCity">Paris</field>
	<field name="ofPhone">+33 14 723 4404</field>
	<field name="ofAdd1">43 Rue Jouffroy D'abbans</field>
	<field name="ofAdd2" />
	<field name="ofState" />
	<field name="ofCountry">France</field>
	<field name="ofPostalCode">75017</field>
	<field name="ofTerritory">EMEA</field>
  </row>

  <row>
	<field name="employeeNumber">1337</field>
	<field name="lastName">Bondur</field>
	<field name="firstName">Loui</field>
	<field name="extension">x6493</field>
	<field name="email">lbondur@classicmodelcars.com</field>
	<field name="reportsTo">1102</field>
	<field name="jobTitle">Sales Rep</field>
	<field name="ofCode">4</field>
	<field name="ofCity">Paris</field>
	<field name="ofPhone">+33 14 723 4404</field>
	<field name="ofAdd1">43 Rue Jouffroy D'abbans</field>
	<field name="ofAdd2" />
	<field name="ofState" />
	<field name="ofCountry">France</field>
	<field name="ofPostalCode">75017</field>
	<field name="ofTerritory">EMEA</field>
  </row>

  <row>
	<field name="employeeNumber">1370</field>
	<field name="lastName">Hernandez</field>
	<field name="firstName">Gerard</field>
	<field name="extension">x2028</field>
	<field name="email">ghernande@classicmodelcars.com</field>
	<field name="reportsTo">1102</field>
	<field name="jobTitle">Sales Rep</field>
	<field name="ofCode">4</field>
	<field name="ofCity">Paris</field>
	<field name="ofPhone">+33 14 723 4404</field>
	<field name="ofAdd1">43 Rue Jouffroy D'abbans</field>
	<field name="ofAdd2" />
	<field name="ofState" />
	<field name="ofCountry">France</field>
	<field name="ofPostalCode">75017</field>
	<field name="ofTerritory">EMEA</field>
  </row>

  <row>
	<field name="employeeNumber">1401</field>
	<field name="lastName">Castillo</field>
	<field name="firstName">Pamela</field>
	<field name="extension">x2759</field>
	<field name="email">pcastillo@classicmodelcars.com</field>
	<field name="reportsTo">1102</field>
	<field name="jobTitle">Sales Rep</field>
	<field name="ofCode">4</field>
	<field name="ofCity">Paris</field>
	<field name="ofPhone">+33 14 723 4404</field>
	<field name="ofAdd1">43 Rue Jouffroy D'abbans</field>
	<field name="ofAdd2" />
	<field name="ofState" />
	<field name="ofCountry">France</field>
	<field name="ofPostalCode">75017</field>
	<field name="ofTerritory">EMEA</field>
  </row>

  <row>
	<field name="employeeNumber">1702</field>
	<field name="lastName">Gerard</field>
	<field name="firstName">Martin</field>
	<field name="extension">x2312</field>
	<field name="email">mgerard@classicmodelcars.com</field>
	<field name="reportsTo">1102</field>
	<field name="jobTitle">Sales Rep</field>
	<field name="ofCode">4</field>
	<field name="ofCity">Paris</field>
	<field name="ofPhone">+33 14 723 4404</field>
	<field name="ofAdd1">43 Rue Jouffroy D'abbans</field>
	<field name="ofAdd2" />
	<field name="ofState" />
	<field name="ofCountry">France</field>
	<field name="ofPostalCode">75017</field>
	<field name="ofTerritory">EMEA</field>
  </row>

  <row>
	<field name="employeeNumber">1621</field>
	<field name="lastName">Nishi</field>
	<field name="firstName">Mami</field>
	<field name="extension">x101</field>
	<field name="email">mnishi@classicmodelcars.com</field>
	<field name="reportsTo">1056</field>
	<field name="jobTitle">Sales Rep</field>
	<field name="ofCode">5</field>
	<field name="ofCity">Tokyo</field>
	<field name="ofPhone">+81 33 224 5000</field>
	<field name="ofAdd1">4-1 Kioicho</field>
	<field name="ofAdd2" />
	<field name="ofState">Chiyoda-Ku</field>
	<field name="ofCountry">Japan</field>
	<field name="ofPostalCode">102-8578</field>
	<field name="ofTerritory">Japan</field>
  </row>

  <row>
	<field name="employeeNumber">1625</field>
	<field name="lastName">Kato</field>
	<field name="firstName">Yoshimi</field>
	<field name="extension">x102</field>
	<field name="email">ykato@classicmodelcars.com</field>
	<field name="reportsTo">1621</field>
	<field name="jobTitle">Sales Rep</field>
	<field name="ofCode">5</field>
	<field name="ofCity">Tokyo</field>
	<field name="ofPhone">+81 33 224 5000</field>
	<field name="ofAdd1">4-1 Kioicho</field>
	<field name="ofAdd2" />
	<field name="ofState">Chiyoda-Ku</field>
	<field name="ofCountry">Japan</field>
	<field name="ofPostalCode">102-8578</field>
	<field name="ofTerritory">Japan</field>
  </row>

  <row>
	<field name="employeeNumber">1088</field>
	<field name="lastName">Patterson</field>
	<field name="firstName">William</field>
	<field name="extension">x4871</field>
	<field name="email">wpatterson@classicmodelcars.com</field>
	<field name="reportsTo">1056</field>
	<field name="jobTitle">Sales Manager (APAC)</field>
	<field name="ofCode">6</field>
	<field name="ofCity">Sydney</field>
	<field name="ofPhone">+61 2 9264 2451</field>
	<field name="ofAdd1">5-11 Wentworth Avenue</field>
	<field name="ofAdd2">Floor #2</field>
	<field name="ofState" />
	<field name="ofCountry">Australia</field>
	<field name="ofPostalCode">NSW 2010</field>
	<field name="ofTerritory">APAC</field>
  </row>

  <row>
	<field name="employeeNumber">1611</field>
	<field name="lastName">Fixter</field>
	<field name="firstName">Andy</field>
	<field name="extension">x101</field>
	<field name="email">afixter@classicmodelcars.com</field>
	<field name="reportsTo">1088</field>
	<field name="jobTitle">Sales Rep</field>
	<field name="ofCode">6</field>
	<field name="ofCity">Sydney</field>
	<field name="ofPhone">+61 2 9264 2451</field>
	<field name="ofAdd1">5-11 Wentworth Avenue</field>
	<field name="ofAdd2">Floor #2</field>
	<field name="ofState" />
	<field name="ofCountry">Australia</field>
	<field name="ofPostalCode">NSW 2010</field>
	<field name="ofTerritory">APAC</field>
  </row>

  <row>
	<field name="employeeNumber">1612</field>
	<field name="lastName">Marsh</field>
	<field name="firstName">Peter</field>
	<field name="extension">x102</field>
	<field name="email">pmarsh@classicmodelcars.com</field>
	<field name="reportsTo">1088</field>
	<field name="jobTitle">Sales Rep</field>
	<field name="ofCode">6</field>
	<field name="ofCity">Sydney</field>
	<field name="ofPhone">+61 2 9264 2451</field>
	<field name="ofAdd1">5-11 Wentworth Avenue</field>
	<field name="ofAdd2">Floor #2</field>
	<field name="ofState" />
	<field name="ofCountry">Australia</field>
	<field name="ofPostalCode">NSW 2010</field>
	<field name="ofTerritory">APAC</field>
  </row>

  <row>
	<field name="employeeNumber">1619</field>
	<field name="lastName">King</field>
	<field name="firstName">Tom</field>
	<field name="extension">x103</field>
	<field name="email">tking@classicmodelcars.com</field>
	<field name="reportsTo">1088</field>
	<field name="jobTitle">Sales Rep</field>
	<field name="ofCode">6</field>
	<field name="ofCity">Sydney</field>
	<field name="ofPhone">+61 2 9264 2451</field>
	<field name="ofAdd1">5-11 Wentworth Avenue</field>
	<field name="ofAdd2">Floor #2</field>
	<field name="ofState" />
	<field name="ofCountry">Australia</field>
	<field name="ofPostalCode">NSW 2010</field>
	<field name="ofTerritory">APAC</field>
  </row>

  <row>
	<field name="employeeNumber">1501</field>
	<field name="lastName">Bott</field>
	<field name="firstName">Larry</field>
	<field name="extension">x2311</field>
	<field name="email">lbott@classicmodelcars.com</field>
	<field name="reportsTo">1102</field>
	<field name="jobTitle">Sales Rep</field>
	<field name="ofCode">7</field>
	<field name="ofCity">London</field>
	<field name="ofPhone">+44 20 7877 2041</field>
	<field name="ofAdd1">25 Old Broad Street</field>
	<field name="ofAdd2">Level 7</field>
	<field name="ofState" />
	<field name="ofCountry">UK</field>
	<field name="ofPostalCode">EC2N 1HN</field>
	<field name="ofTerritory">EMEA</field>
  </row>

  <row>
	<field name="employeeNumber">1504</field>
	<field name="lastName">Jones</field>
	<field name="firstName">Barry</field>
	<field name="extension">x102</field>
	<field name="email">bjones@classicmodelcars.com</field>
	<field name="reportsTo">1102</field>
	<field name="jobTitle">Sales Rep</field>
	<field name="ofCode">7</field>
	<field name="ofCity">London</field>
	<field name="ofPhone">+44 20 7877 2041</field>
	<field name="ofAdd1">25 Old Broad Street</field>
	<field name="ofAdd2">Level 7</field>
	<field name="ofState" />
	<field name="ofCountry">UK</field>
	<field name="ofPostalCode">EC2N 1HN</field>
	<field name="ofTerritory">EMEA</field>
  </row>
</resultset>
