<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resultset [
  <!ELEMENT resultset (row*)>
  <!ELEMENT row (field*)>
  <!ELEMENT field (#PCDATA)>
  <!ATTLIST field name CDATA #REQUIRED>
]>
<resultset>
  <row>
	<field name="customerNumber">103</field>
	<field name="checkNumber">HQ336336</field>
	<field name="paymentDate">2004-10-19</field>
	<field name="amount">6066.78</field>
	<field name="customerName">Atelier graphique</field>
	<field name="contactLastName">Schmitt</field>
	<field name="contactFirstName">Carine </field>
	<field name="phone">40.32.2555</field>
	<field name="addressLine1">54, rue Royale</field>
	<field name="addressLine2" />
	<field name="city">Nantes</field>
	<field name="state" />
	<field name="postalCode">44000</field>
	<field name="country">France</field>
	<field name="salesRepEmployeeNumber">1370</field>
	<field name="creditLimit">21000.00</field>
  </row>

  <row>
	<field name="customerNumber">103</field>
	<field name="checkNumber">JM555205</field>
	<field name="paymentDate">2003-06-05</field>
	<field name="amount">14571.44</field>
	<field name="customerName">Atelier graphique</field>
	<field name="contactLastName">Schmitt</field>
	<field name="contactFirstName">Carine </field>
	<field name="phone">40.32.2555</field>
	<field name="addressLine1">54, rue Royale</field>
	<field name="addressLine2" />
	<field name="city">Nantes</field>
	<field name="state" />
	<field name="postalCode">44000</field>
	<field name="country">France</field>
	<field name="salesRepEmployeeNumber">1370</field>
	<field name="creditLimit">21000.00</field>
  </row>

  <row>
	<field name="customerNumber">103</field>
	<field name="checkNumber">OM314933</field>
	<field name="paymentDate">2004-12-18</field>
	<field name="amount">1676.14</field>
	<field name="customerName">Atelier graphique</field>
	<field name="contactLastName">Schmitt</field>
	<field name="contactFirstName">Carine </field>
	<field name="phone">40.32.2555</field>
	<field name="addressLine1">54, rue Royale</field>
	<field name="addressLine2" />
	<field name="city">Nantes</field>
	<field name="state" />
	<field name="postalCode">44000</field>
	<field name="country">France</field>
	<field name="salesRepEmployeeNumber">1370</field>
	<field name="creditLimit">21000.00</field>
  </row>

  <row>
	<field name="customerNumber">112</field>
	<field name="checkNumber">BO864823</field>
	<field name="paymentDate">2004-12-17</field>
	<field name="amount">14191.12</field>
	<field name="customerName">Signal Gift Stores</field>
	<field name="contactLastName">King</field>
	<field name="contactFirstName">Jean</field>
	<field name="phone">7025551838</field>
	<field name="addressLine1">8489 Strong St.</field>
	<field name="addressLine2" />
	<field name="city">Las Vegas</field>
	<field name="state">NV</field>
	<field name="postalCode">83030</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1166</field>
	<field name="creditLimit">71800.00</field>
  </row>

  <row>
	<field name="customerNumber">112</field>
	<field name="checkNumber">HQ55022</field>
	<field name="paymentDate">2003-06-06</field>
	<field name="amount">32641.98</field>
	<field name="customerName">Signal Gift Stores</field>
	<field name="contactLastName">King</field>
	<field name="contactFirstName">Jean</field>
	<field name="phone">7025551838</field>
	<field name="addressLine1">8489 Strong St.</field>
	<field name="addressLine2" />
	<field name="city">Las Vegas</field>
	<field name="state">NV</field>
	<field name="postalCode">83030</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1166</field>
	<field name="creditLimit">71800.00</field>
  </row>

  <row>
	<field name="customerNumber">112</field>
	<field name="checkNumber">ND748579</field>
	<field name="paymentDate">2004-08-20</field>
	<field name="amount">33347.88</field>
	<field name="customerName">Signal Gift Stores</field>
	<field name="contactLastName">King</field>
	<field name="contactFirstName">Jean</field>
	<field name="phone">7025551838</field>
	<field name="addressLine1">8489 Strong St.</field>
	<field name="addressLine2" />
	<field name="city">Las Vegas</field>
	<field name="state">NV</field>
	<field name="postalCode">83030</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1166</field>
	<field name="creditLimit">71800.00</field>
  </row>

  <row>
	<field name="customerNumber">114</field>
	<field name="checkNumber">GG31455</field>
	<field name="paymentDate">2003-05-20</field>
	<field name="amount">45864.03</field>
	<field name="customerName">Australian Collectors, Co.</field>
	<field name="contactLastName">Ferguson</field>
	<field name="contactFirstName">Peter</field>
	<field name="phone">03 9520 4555</field>
	<field name="addressLine1">636 St Kilda Road</field>
	<field name="addressLine2">Level 3</field>
	<field name="city">Melbourne</field>
	<field name="state">Victoria</field>
	<field name="postalCode">3004</field>
	<field name="country">Australia</field>
	<field name="salesRepEmployeeNumber">1611</field>
	<field name="creditLimit">117300.00</field>
  </row>

  <row>
	<field name="customerNumber">114</field>
	<field name="checkNumber">MA765515</field>
	<field name="paymentDate">2004-12-15</field>
	<field name="amount">82261.22</field>
	<field name="customerName">Australian Collectors, Co.</field>
	<field name="contactLastName">Ferguson</field>
	<field name="contactFirstName">Peter</field>
	<field name="phone">03 9520 4555</field>
	<field name="addressLine1">636 St Kilda Road</field>
	<field name="addressLine2">Level 3</field>
	<field name="city">Melbourne</field>
	<field name="state">Victoria</field>
	<field name="postalCode">3004</field>
	<field name="country">Australia</field>
	<field name="salesRepEmployeeNumber">1611</field>
	<field name="creditLimit">117300.00</field>
  </row>

  <row>
	<field name="customerNumber">114</field>
	<field name="checkNumber">NP603840</field>
	<field name="paymentDate">2003-05-31</field>
	<field name="amount">7565.08</field>
	<field name="customerName">Australian Collectors, Co.</field>
	<field name="contactLastName">Ferguson</field>
	<field name="contactFirstName">Peter</field>
	<field name="phone">03 9520 4555</field>
	<field name="addressLine1">636 St Kilda Road</field>
	<field name="addressLine2">Level 3</field>
	<field name="city">Melbourne</field>
	<field name="state">Victoria</field>
	<field name="postalCode">3004</field>
	<field name="country">Australia</field>
	<field name="salesRepEmployeeNumber">1611</field>
	<field name="creditLimit">117300.00</field>
  </row>

  <row>
	<field name="customerNumber">114</field>
	<field name="checkNumber">NR27552</field>
	<field name="paymentDate">2004-03-10</field>
	<field name="amount">44894.74</field>
	<field name="customerName">Australian Collectors, Co.</field>
	<field name="contactLastName">Ferguson</field>
	<field name="contactFirstName">Peter</field>
	<field name="phone">03 9520 4555</field>
	<field name="addressLine1">636 St Kilda Road</field>
	<field name="addressLine2">Level 3</field>
	<field name="city">Melbourne</field>
	<field name="state">Victoria</field>
	<field name="postalCode">3004</field>
	<field name="country">Australia</field>
	<field name="salesRepEmployeeNumber">1611</field>
	<field name="creditLimit">117300.00</field>
  </row>

  <row>
	<field name="customerNumber">119</field>
	<field name="checkNumber">DB933704</field>
	<field name="paymentDate">2004-11-14</field>
	<field name="amount">19501.82</field>
	<field name="customerName">La Rochelle Gifts</field>
	<field name="contactLastName">Labrune</field>
	<field name="contactFirstName">Janine </field>
	<field name="phone">40.67.8555</field>
	<field name="addressLine1">67, rue des Cinquante Otages</field>
	<field name="addressLine2" />
	<field name="city">Nantes</field>
	<field name="state" />
	<field name="postalCode">44000</field>
	<field name="country">France</field>
	<field name="salesRepEmployeeNumber">1370</field>
	<field name="creditLimit">118200.00</field>
  </row>

  <row>
	<field name="customerNumber">119</field>
	<field name="checkNumber">LN373447</field>
	<field name="paymentDate">2004-08-08</field>
	<field name="amount">47924.19</field>
	<field name="customerName">La Rochelle Gifts</field>
	<field name="contactLastName">Labrune</field>
	<field name="contactFirstName">Janine </field>
	<field name="phone">40.67.8555</field>
	<field name="addressLine1">67, rue des Cinquante Otages</field>
	<field name="addressLine2" />
	<field name="city">Nantes</field>
	<field name="state" />
	<field name="postalCode">44000</field>
	<field name="country">France</field>
	<field name="salesRepEmployeeNumber">1370</field>
	<field name="creditLimit">118200.00</field>
  </row>

  <row>
	<field name="customerNumber">119</field>
	<field name="checkNumber">NG94694</field>
	<field name="paymentDate">2005-02-22</field>
	<field name="amount">49523.67</field>
	<field name="customerName">La Rochelle Gifts</field>
	<field name="contactLastName">Labrune</field>
	<field name="contactFirstName">Janine </field>
	<field name="phone">40.67.8555</field>
	<field name="addressLine1">67, rue des Cinquante Otages</field>
	<field name="addressLine2" />
	<field name="city">Nantes</field>
	<field name="state" />
	<field name="postalCode">44000</field>
	<field name="country">France</field>
	<field name="salesRepEmployeeNumber">1370</field>
	<field name="creditLimit">118200.00</field>
  </row>

  <row>
	<field name="customerNumber">121</field>
	<field name="checkNumber">DB889831</field>
	<field name="paymentDate">2003-02-16</field>
	<field name="amount">50218.95</field>
	<field name="customerName">Baane Mini Imports</field>
	<field name="contactLastName">Bergulfsen</field>
	<field name="contactFirstName">Jonas </field>
	<field name="phone">07-98 9555</field>
	<field name="addressLine1">Erling Skakkes gate 78</field>
	<field name="addressLine2" />
	<field name="city">Stavern</field>
	<field name="state" />
	<field name="postalCode">4110</field>
	<field name="country">Norway</field>
	<field name="salesRepEmployeeNumber">1504</field>
	<field name="creditLimit">81700.00</field>
  </row>

  <row>
	<field name="customerNumber">121</field>
	<field name="checkNumber">FD317790</field>
	<field name="paymentDate">2003-10-28</field>
	<field name="amount">1491.38</field>
	<field name="customerName">Baane Mini Imports</field>
	<field name="contactLastName">Bergulfsen</field>
	<field name="contactFirstName">Jonas </field>
	<field name="phone">07-98 9555</field>
	<field name="addressLine1">Erling Skakkes gate 78</field>
	<field name="addressLine2" />
	<field name="city">Stavern</field>
	<field name="state" />
	<field name="postalCode">4110</field>
	<field name="country">Norway</field>
	<field name="salesRepEmployeeNumber">1504</field>
	<field name="creditLimit">81700.00</field>
  </row>

  <row>
	<field name="customerNumber">121</field>
	<field name="checkNumber">KI831359</field>
	<field name="paymentDate">2004-11-04</field>
	<field name="amount">17876.32</field>
	<field name="customerName">Baane Mini Imports</field>
	<field name="contactLastName">Bergulfsen</field>
	<field name="contactFirstName">Jonas </field>
	<field name="phone">07-98 9555</field>
	<field name="addressLine1">Erling Skakkes gate 78</field>
	<field name="addressLine2" />
	<field name="city">Stavern</field>
	<field name="state" />
	<field name="postalCode">4110</field>
	<field name="country">Norway</field>
	<field name="salesRepEmployeeNumber">1504</field>
	<field name="creditLimit">81700.00</field>
  </row>

  <row>
	<field name="customerNumber">121</field>
	<field name="checkNumber">MA302151</field>
	<field name="paymentDate">2004-11-28</field>
	<field name="amount">34638.14</field>
	<field name="customerName">Baane Mini Imports</field>
	<field name="contactLastName">Bergulfsen</field>
	<field name="contactFirstName">Jonas </field>
	<field name="phone">07-98 9555</field>
	<field name="addressLine1">Erling Skakkes gate 78</field>
	<field name="addressLine2" />
	<field name="city">Stavern</field>
	<field name="state" />
	<field name="postalCode">4110</field>
	<field name="country">Norway</field>
	<field name="salesRepEmployeeNumber">1504</field>
	<field name="creditLimit">81700.00</field>
  </row>

  <row>
	<field name="customerNumber">124</field>
	<field name="checkNumber">AE215433</field>
	<field name="paymentDate">2005-03-05</field>
	<field name="amount">101244.59</field>
	<field name="customerName">Mini Gifts Distributors Ltd.</field>
	<field name="contactLastName">Nelson</field>
	<field name="contactFirstName">Susan</field>
	<field name="phone">4155551450</field>
	<field name="addressLine1">5677 Strong St.</field>
	<field name="addressLine2" />
	<field name="city">San Rafael</field>
	<field name="state">CA</field>
	<field name="postalCode">97562</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1165</field>
	<field name="creditLimit">210500.00</field>
  </row>

  <row>
	<field name="customerNumber">124</field>
	<field name="checkNumber">BG255406</field>
	<field name="paymentDate">2004-08-28</field>
	<field name="amount">85410.87</field>
	<field name="customerName">Mini Gifts Distributors Ltd.</field>
	<field name="contactLastName">Nelson</field>
	<field name="contactFirstName">Susan</field>
	<field name="phone">4155551450</field>
	<field name="addressLine1">5677 Strong St.</field>
	<field name="addressLine2" />
	<field name="city">San Rafael</field>
	<field name="state">CA</field>
	<field name="postalCode">97562</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1165</field>
	<field name="creditLimit">210500.00</field>
  </row>

  <row>
	<field name="customerNumber">124</field>
	<field name="checkNumber">CQ287967</field>
	<field name="paymentDate">2003-04-11</field>
	<field name="amount">11044.30</field>
	<field name="customerName">Mini Gifts Distributors Ltd.</field>
	<field name="contactLastName">Nelson</field>
	<field name="contactFirstName">Susan</field>
	<field name="phone">4155551450</field>
	<field name="addressLine1">5677 Strong St.</field>
	<field name="addressLine2" />
	<field name="city">San Rafael</field>
	<field name="state">CA</field>
	<field name="postalCode">97562</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1165</field>
	<field name="creditLimit">210500.00</field>
  </row>

  <row>
	<field name="customerNumber">124</field>
	<field name="checkNumber">ET64396</field>
	<field name="paymentDate">2005-04-16</field>
	<field name="amount">83598.04</field>
	<field name="customerName">Mini Gifts Distributors Ltd.</field>
	<field name="contactLastName">Nelson</field>
	<field name="contactFirstName">Susan</field>
	<field name="phone">4155551450</field>
	<field name="addressLine1">5677 Strong St.</field>
	<field name="addressLine2" />
	<field name="city">San Rafael</field>
	<field name="state">CA</field>
	<field name="postalCode">97562</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1165</field>
	<field name="creditLimit">210500.00</field>
  </row>

  <row>
	<field name="customerNumber">124</field>
	<field name="checkNumber">HI366474</field>
	<field name="paymentDate">2004-12-27</field>
	<field name="amount">47142.70</field>
	<field name="customerName">Mini Gifts Distributors Ltd.</field>
	<field name="contactLastName">Nelson</field>
	<field name="contactFirstName">Susan</field>
	<field name="phone">4155551450</field>
	<field name="addressLine1">5677 Strong St.</field>
	<field name="addressLine2" />
	<field name="city">San Rafael</field>
	<field name="state">CA</field>
	<field name="postalCode">97562</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1165</field>
	<field name="creditLimit">210500.00</field>
  </row>

  <row>
	<field name="customerNumber">124</field>
	<field name="checkNumber">HR86578</field>
	<field name="paymentDate">2004-11-02</field>
	<field name="amount">55639.66</field>
	<field name="customerName">Mini Gifts Distributors Ltd.</field>
	<field name="contactLastName">Nelson</field>
	<field name="contactFirstName">Susan</field>
	<field name="phone">4155551450</field>
	<field name="addressLine1">5677 Strong St.</field>
	<field name="addressLine2" />
	<field name="city">San Rafael</field>
	<field name="state">CA</field>
	<field name="postalCode">97562</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1165</field>
	<field name="creditLimit">210500.00</field>
  </row>

  <row>
	<field name="customerNumber">124</field>
	<field name="checkNumber">KI131716</field>
	<field name="paymentDate">2003-08-15</field>
	<field name="amount">111654.40</field>
	<field name="customerName">Mini Gifts Distributors Ltd.</field>
	<field name="contactLastName">Nelson</field>
	<field name="contactFirstName">Susan</field>
	<field name="phone">4155551450</field>
	<field name="addressLine1">5677 Strong St.</field>
	<field name="addressLine2" />
	<field name="city">San Rafael</field>
	<field name="state">CA</field>
	<field name="postalCode">97562</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1165</field>
	<field name="creditLimit">210500.00</field>
  </row>

  <row>
	<field name="customerNumber">124</field>
	<field name="checkNumber">LF217299</field>
	<field name="paymentDate">2004-03-26</field>
	<field name="amount">43369.30</field>
	<field name="customerName">Mini Gifts Distributors Ltd.</field>
	<field name="contactLastName">Nelson</field>
	<field name="contactFirstName">Susan</field>
	<field name="phone">4155551450</field>
	<field name="addressLine1">5677 Strong St.</field>
	<field name="addressLine2" />
	<field name="city">San Rafael</field>
	<field name="state">CA</field>
	<field name="postalCode">97562</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1165</field>
	<field name="creditLimit">210500.00</field>
  </row>

  <row>
	<field name="customerNumber">124</field>
	<field name="checkNumber">NT141748</field>
	<field name="paymentDate">2003-11-25</field>
	<field name="amount">45084.38</field>
	<field name="customerName">Mini Gifts Distributors Ltd.</field>
	<field name="contactLastName">Nelson</field>
	<field name="contactFirstName">Susan</field>
	<field name="phone">4155551450</field>
	<field name="addressLine1">5677 Strong St.</field>
	<field name="addressLine2" />
	<field name="city">San Rafael</field>
	<field name="state">CA</field>
	<field name="postalCode">97562</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1165</field>
	<field name="creditLimit">210500.00</field>
  </row>

  <row>
	<field name="customerNumber">128</field>
	<field name="checkNumber">DI925118</field>
	<field name="paymentDate">2003-01-28</field>
	<field name="amount">10549.01</field>
	<field name="customerName">Blauer See Auto, Co.</field>
	<field name="contactLastName">Keitel</field>
	<field name="contactFirstName">Roland</field>
	<field name="phone">+49 69 66 90 2555</field>
	<field name="addressLine1">Lyonerstr. 34</field>
	<field name="addressLine2" />
	<field name="city">Frankfurt</field>
	<field name="state" />
	<field name="postalCode">60528</field>
	<field name="country">Germany</field>
	<field name="salesRepEmployeeNumber">1504</field>
	<field name="creditLimit">59700.00</field>
  </row>

  <row>
	<field name="customerNumber">128</field>
	<field name="checkNumber">FA465482</field>
	<field name="paymentDate">2003-10-18</field>
	<field name="amount">24101.81</field>
	<field name="customerName">Blauer See Auto, Co.</field>
	<field name="contactLastName">Keitel</field>
	<field name="contactFirstName">Roland</field>
	<field name="phone">+49 69 66 90 2555</field>
	<field name="addressLine1">Lyonerstr. 34</field>
	<field name="addressLine2" />
	<field name="city">Frankfurt</field>
	<field name="state" />
	<field name="postalCode">60528</field>
	<field name="country">Germany</field>
	<field name="salesRepEmployeeNumber">1504</field>
	<field name="creditLimit">59700.00</field>
  </row>

  <row>
	<field name="customerNumber">128</field>
	<field name="checkNumber">FH668230</field>
	<field name="paymentDate">2004-03-24</field>
	<field name="amount">33820.62</field>
	<field name="customerName">Blauer See Auto, Co.</field>
	<field name="contactLastName">Keitel</field>
	<field name="contactFirstName">Roland</field>
	<field name="phone">+49 69 66 90 2555</field>
	<field name="addressLine1">Lyonerstr. 34</field>
	<field name="addressLine2" />
	<field name="city">Frankfurt</field>
	<field name="state" />
	<field name="postalCode">60528</field>
	<field name="country">Germany</field>
	<field name="salesRepEmployeeNumber">1504</field>
	<field name="creditLimit">59700.00</field>
  </row>

  <row>
	<field name="customerNumber">128</field>
	<field name="checkNumber">IP383901</field>
	<field name="paymentDate">2004-11-18</field>
	<field name="amount">7466.32</field>
	<field name="customerName">Blauer See Auto, Co.</field>
	<field name="contactLastName">Keitel</field>
	<field name="contactFirstName">Roland</field>
	<field name="phone">+49 69 66 90 2555</field>
	<field name="addressLine1">Lyonerstr. 34</field>
	<field name="addressLine2" />
	<field name="city">Frankfurt</field>
	<field name="state" />
	<field name="postalCode">60528</field>
	<field name="country">Germany</field>
	<field name="salesRepEmployeeNumber">1504</field>
	<field name="creditLimit">59700.00</field>
  </row>

  <row>
	<field name="customerNumber">129</field>
	<field name="checkNumber">DM826140</field>
	<field name="paymentDate">2004-12-08</field>
	<field name="amount">26248.78</field>
	<field name="customerName">Mini Wheels Co.</field>
	<field name="contactLastName">Murphy</field>
	<field name="contactFirstName">Julie</field>
	<field name="phone">6505555787</field>
	<field name="addressLine1">5557 North Pendale Street</field>
	<field name="addressLine2" />
	<field name="city">San Francisco</field>
	<field name="state">CA</field>
	<field name="postalCode">94217</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1165</field>
	<field name="creditLimit">64600.00</field>
  </row>

  <row>
	<field name="customerNumber">129</field>
	<field name="checkNumber">ID449593</field>
	<field name="paymentDate">2003-12-11</field>
	<field name="amount">23923.93</field>
	<field name="customerName">Mini Wheels Co.</field>
	<field name="contactLastName">Murphy</field>
	<field name="contactFirstName">Julie</field>
	<field name="phone">6505555787</field>
	<field name="addressLine1">5557 North Pendale Street</field>
	<field name="addressLine2" />
	<field name="city">San Francisco</field>
	<field name="state">CA</field>
	<field name="postalCode">94217</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1165</field>
	<field name="creditLimit">64600.00</field>
  </row>

  <row>
	<field name="customerNumber">129</field>
	<field name="checkNumber">PI42991</field>
	<field name="paymentDate">2003-04-09</field>
	<field name="amount">16537.85</field>
	<field name="customerName">Mini Wheels Co.</field>
	<field name="contactLastName">Murphy</field>
	<field name="contactFirstName">Julie</field>
	<field name="phone">6505555787</field>
	<field name="addressLine1">5557 North Pendale Street</field>
	<field name="addressLine2" />
	<field name="city">San Francisco</field>
	<field name="state">CA</field>
	<field name="postalCode">94217</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1165</field>
	<field name="creditLimit">64600.00</field>
  </row>

  <row>
	<field name="customerNumber">131</field>
	<field name="checkNumber">CL442705</field>
	<field name="paymentDate">2003-03-12</field>
	<field name="amount">22292.62</field>
	<field name="customerName">Land of Toys Inc.</field>
	<field name="contactLastName">Lee</field>
	<field name="contactFirstName">Kwai</field>
	<field name="phone">2125557818</field>
	<field name="addressLine1">897 Long Airport Avenue</field>
	<field name="addressLine2" />
	<field name="city">NYC</field>
	<field name="state">NY</field>
	<field name="postalCode">10022</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1323</field>
	<field name="creditLimit">114900.00</field>
  </row>

  <row>
	<field name="customerNumber">131</field>
	<field name="checkNumber">MA724562</field>
	<field name="paymentDate">2004-12-02</field>
	<field name="amount">50025.35</field>
	<field name="customerName">Land of Toys Inc.</field>
	<field name="contactLastName">Lee</field>
	<field name="contactFirstName">Kwai</field>
	<field name="phone">2125557818</field>
	<field name="addressLine1">897 Long Airport Avenue</field>
	<field name="addressLine2" />
	<field name="city">NYC</field>
	<field name="state">NY</field>
	<field name="postalCode">10022</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1323</field>
	<field name="creditLimit">114900.00</field>
  </row>

  <row>
	<field name="customerNumber">131</field>
	<field name="checkNumber">NB445135</field>
	<field name="paymentDate">2004-09-11</field>
	<field name="amount">35321.97</field>
	<field name="customerName">Land of Toys Inc.</field>
	<field name="contactLastName">Lee</field>
	<field name="contactFirstName">Kwai</field>
	<field name="phone">2125557818</field>
	<field name="addressLine1">897 Long Airport Avenue</field>
	<field name="addressLine2" />
	<field name="city">NYC</field>
	<field name="state">NY</field>
	<field name="postalCode">10022</field>
	<field name="country">USA</field>
	<field name="salesRepEmployeeNumber">1323</field>
	<field name="creditLimit">114900.00</field>
  </row>

  <row>
	<field name="customerNumber">141</field>
	<field name="checkNumber">AU364101</field>
	<field name="paymentDate">2003-07-19</field>
	<field name="amount">36251.03</field>
	<field name="customerName">Euro+ Shopping Channel</field>
	<field name="contactLastName">Freyre</field>
	<field name="contactFirstName">Diego </field>
	<field name="phone">(91) 555 94 44</field>
	<field name="addressLine1">C/ Moralzarzal, 86</field>
	<field name="addressLine2" />
	<field name="city">Madrid</field>
	<field name="state" />
	<field name="postalCode">28034</field>
	<field name="country">Spain</field>
	<field name="salesRepEmployeeNumber">1370</field>
	<field name="creditLimit">227600.00</field>
  </row>

  <row>
	<field name="customerNumber">141</field>
	<field name="checkNumber">DB583216</field>
	<field name="paymentDate">2004-11-01</field>
	<field name="amount">36140.38</field>
	<field name="customerName">Euro+ Shopping Channel</field>
	<field name="contactLastName">Freyre</field>
	<field name="contactFirstName">Diego </field>
	<field name="phone">(91) 555 94 44</field>
	<field name="addressLine1">C/ Moralzarzal, 86</field>
	<field name="addressLine2" />
	<field name="city">Madrid</field>
	<field name="state" />
	<field name="postalCode">28034</field>
	<field name="country">Spain</field>
	<field name="salesRepEmployeeNumber">1370</field>
	<field name="creditLimit">227600.00</field>
  </row>

  <row>
	<field name="customerNumber">141</field>
	<field name="checkNumber">DL460618</field>
	<field name="paymentDate">2005-05-19</field>
	<field name="amount">46895.48</field>
	<field name="customerName">Euro+ Shopping Channel</field>
	<field name="contactLastName">Freyre</field>
	<field name="contactFirstName">Diego </field>
	<field name="phone">(91) 555 94 44</field>
	<field name="addressLine1">C/ Moralzarzal, 86</field>
	<field name="addressLine2" />
	<field name="city">Madrid</field>
	<field name="state" />
	<field name="postalCode">28034</field>
	<field name="country">Spain</field>
	<field name="salesRepEmployeeNumber">1370</field>
	<field name="creditLimit">227600.00</field>
  </row>

  <row>
	<field name="customerNumber">141</field>
	<field name="checkNumber">HJ32686</field>
	<field name="paymentDate">2004-01-30</field>
	<field name="amount">59830.55</field>
	<field name="customerName">Euro+ Shopping Channel</field>
	<field name="contactLastName">Freyre</field>
	<field name="contactFirstName">Diego </field>
	<field name="phone">(91) 555 94 44</field>
	<field name="addressLine1">C/ Moralzarzal, 86</field>
	<field name="addressLine2" />
	<field name="city">Madrid</field>
	<field name="state" />
	<field name="postalCode">28034</field>
	<field name="country">Spain</field>
	<field name="salesRepEmployeeNumber">1370</field>
	<field name="creditLimit">227600.00</field>
  </row>

  <row>
	<field name="customerNumber">141</field>
	<field name="checkNumber">ID10962</field>
	<field name="paymentDate">2004-12-31</field>
	<field name="amount">116208.40</field>
	<field name="customerName">Euro+ Shopping Channel</field>
	<field name="contactLastName">Freyre</field>
	<field name="contactFirstName">Diego </field>
	<field name="phone">(91) 555 94 44</field>
	<field name="addressLine1">C/ Moralzarzal, 86</field>
	<field name="addressLine2" />
	<field name="city">Madrid</field>
	<field name="state" />
	<field name="postalCode">28034</field>
	<field name="country">Spain</field>
	<field name="salesRepEmployeeNumber">1370</field>
	<field name="creditLimit">227600.00</field>
  </row>

  <row>